FROM openjdk
RUN wget "https://raw.githubusercontent.com/achoimet/docker-formation/master/TP2%20-%20Construction%20d'un%20Dockerfile/TwentyOneSticks.java"
RUN javac ./TwentyOneSticks.java
RUN java ./TwentyOneSticks